db:
  build: db
  volumes:
    # Host provider specific disk/claim
    - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    # HostPathVolumeSource
    - /etc/localtime:/etc/localtime:ro
app:
  build: app
  # Docker links: allow you to connect two Docker containers together
  links:
    - db:db
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
web:
  build: web
  ports:
    - "443:443"
  links:
    - app:platform
  volumes:
    - /etc/localtime:/etc/localtime:ro
