apiVersion: v1
kind: ReplicationController
metadata:
  name: mattermost-app
spec:
  replicas: 1
  selector:
    app: mattermost-app
  template:
    metadata:
      labels:
        app: mattermost-app
    spec:
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
    # Google Cloud Platform Persistent Volume Disk
      # - name: assets
      #   gcePersistentDisk:
      #     pdName: mattermost-assets
      #     fsType: "ext4"
      #
      # - name: postgres
      #   gcePersistentDisk:
      #     pdName: mattermost-postgres
      #     fsType: "ext4" 
      restartPolicy: Always
