apiVersion: v1
kind: ReplicationController
metadata:
  name: mattermost-app
spec:
  replicas: 1
  selector:
    app: mattermost-app
  template:
    metadata:
      labels:
        app: mattermost-app
    spec:
      containers:
      - name: app
        image: redspreadapps/mattermost-app:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
    # Must complete commented out section below
        - name: assets
          mountPath: /mattermost/data
        ports:
        - containerPort: 80
          protocol: TCP
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
     # Google Cloud Platform Persistent Volume Disk
      - name: assets
        gcePersistentDisk:
          pdName: mattermost-assets
          fsType: "ext4"
     # AWS Persistent Volume Disk
     # - name: assets
     #   awsElasticBlockStore:
     #     volumeID: mattermost-assets
     #     fsType: "ext4"
      restartPolicy: Always