apiVersion: v1
kind: ReplicationController
metadata:
  name: mattermost-db
spec:
  replicas: 1
  selector:
    app: mattermost-db
  template:
    metadata:
      labels:
        app: mattermost-db
    spec:
      containers:
      - name: db
        image: redspreadapps/mattermost-db:1
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: pgauth
          mountPath: /etc/secrets
     # Uncomment this for production use
        # - name: postgres
        #   mountPath: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
      volumes:
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: pgauth
        secret:
          secretName: postgres-credsA
     #  Google Cloud Platform Persistent Volume Disk
      # - name: postgres
      #   gcePersistentDisk:
      #     pdName: mattermost-postgres
      #     fsType: "ext4"
      restartPolicy: Always
